/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.indiantechnicalsupport.debatingutility;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(2, "app should have a greeting");
    }
}
